# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class ApplePhotosExport < Formula
  desc "Command line tool to export photos from the macos photos library, organized by a"
  homepage "https://github.com/haukesomm/apple-photos-export"
  url "https://github.com/haukesomm/apple-photos-export/archive/refs/tags/v1.4.0.tar.gz"
  version "1.4.0"
  sha256 "f20df4e864692911060772dc98248e25f3bd98ac879652953c1abb95daafd630"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/haukesomm/apple-photos-export/releases/download/v1.4.0/apple-photos-export-1.4.0-darwin-arm64.tar.gz"
      sha256 "ace215e478872047c84f3bdf1fd5e1991ee79c3080d714a4d33d39b7aa4df519"
    end
  end

  def install
    bin.install "apple-photos-export"
  end
end
